### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [roberer/optileloader#1]
# Problem

Please remove https://github.com/roberer/optileloader/tree/main/__pycache__
it is generated on install

**Comment by robermaps** [comment]
Done! Thank you.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: mazano ***@***.***>
Sent: Monday, January 3, 2022 9:30:33 PM
To: roberer/optileloader ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [roberer/optileloader] Plugin approval (Issue #1)


Problem

Please remove https://github.com/roberer/optileloader/tree/main/__pycache__
it is generated on install

**Comment by robermaps** [comment]
Fixed
